services:
  festens-midtpunkt:
    build: .
    container_name: festens_midtpunkt
    restart: unless-stopped

    environment:
      PORT: "3000"

    ports:
      - "30050:3000"

    volumes:
      - ./server/data:/app/server/data
